FROM edbizarro/gitlab-ci-pipeline-php:8

USER root
RUN docker-php-ext-install sockets sysvsem

# Disable XDebug
RUN rm -rf /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN pecl install pcov

RUN docker-php-ext-enable pcov
